server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/evently-db
    username: postgres
    password: klu@321
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # Flyway handles schema, avoid auto DDL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: evently-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        isolation.level: read_committed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 5
        batch.size: 16384
    listener:
      ack-mode: manual
      concurrency: 3 # parallel consumer threads per container

  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  info:
    env:
      enabled: true
